name: "\U0001F4A1 Feature request"
description: Suggest an idea for this project
title: "\U0001F4A1 [FEAT]"
labels: ["enhancement"]
body:
    - type: textarea
      attributes:
        label: Is your feature request related to a problem? 😢 Please describe.
        description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
        placeholder: |
          Your description goes here...
        
    - type: textarea
      attributes:
          label: Describe the solution you'd like 🤔
          description: A clear and concise description of what you want to happen.
          placeholder: |
            Your description goes here...
          
    - type: textarea
      attributes:
        label: Describe alternatives you've considered 🧐
        description: A clear and concise description of any alternative solutions or features you've considered.
        placeholder: |
          Your description goes here...

    - type: textarea
      attributes:
        label: Additional context 📝
        description: Add any other context about the problem here.
        placeholder: |
          Your additional context goes here...
        
        
